name: Pull request (PR) checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title
        uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            test
            refactor
            chore
            ci
          requireScope: false

  pr-size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Check PR size
        run: |
          git fetch origin main
          CHANGED_FILES=$(git diff --name-only origin/main...HEAD | wc -l)
          CHANGED_LINES=$(git diff --stat origin/main...HEAD | tail -1 | awk '{print $4+$6}')

          echo "Changed files: $CHANGED_FILES"
          echo "Changed lines: $CHANGED_LINES"

          if [ "$CHANGED_FILES" -gt 50 ]; then
            echo "::warning::This PR changes $CHANGED_FILES files. Consider splitting into smaller PRs."
          fi

          if [ "$CHANGED_LINES" -gt 1000 ]; then
            echo "::warning::This PR changes $CHANGED_LINES lines. Consider splitting into smaller PRs."
          fi

  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Check for print statements
        run: |
          if grep -r "print(" src/ --include="*.py" | grep -v "__main__.py"; then
            echo "::warning::Found print() statements in source code. Consider using logging instead."
          fi

      - name: Check for TODO comments
        run: |
          if grep -r "TODO" src/ --include="*.py"; then
            echo "::notice::Found TODO comments in source code."
          fi
